cm_core_homepage:
    path:     /
    methods: [GET]
    defaults: { _controller: CMCoreBundle:Default:index }

cm_core_add_contact:
    path:     /Ajouter-un-contact
    methods: [GET]
    defaults: { _controller: CMCoreBundle:Default:add }