cm_core_homepage:
    path:     /
    methods: [GET]
    defaults: { _controller: CMCoreBundle:Core:index }

cm_core_add_contact:
    path:     /Ajouter-un-contact
    methods: [GET, POST]
    defaults: { _controller: CMCoreBundle:Core:add }

cm_core_edit_contact:
    path:     /Modifier-un-contact/{idContact}
    methods: [GET, POST]
    defaults: { _controller: CMCoreBundle:Core:edit }

cm_core_delete_contact:
    path:     /Supprimer-un-contact/{idContact}
    methods: [POST]
    defaults: { _controller: CMCoreBundle:Core:delete }